Modificação da estrutura de pastas base
Sysvale/cookiecutter-data-science pull request #1
Opened 2020-06-04 13:23 UTC by LEMSantos

2020-06-04 19:05 UTC, elaynelemos requested changes
Sugiro que remova a variável de entrada para licença no `cookiecutter.json`. Além de verificar se alguma referências à licença no template ficou para trás.

2020-06-04 19:07 UTC, elaynelemos requested changes
Falta adicionar o `env.example.py`.

2020-06-04 19:12 UTC, elaynelemos requested changes
Adicionar `pytest-cov` às dependências de dev.

2020-06-04 20:38 UTC, LEMSantos commented
> Falta adicionar o `env.example.py`.

Está lá, tu que não viu kkkkk

2020-06-04 20:39 UTC, LEMSantos commented
> Sugiro que remova a variável de entrada para licença no `cookiecutter.json`. Além de verificar se alguma referências à licença no template ficou para trás.

Ja foi removido, tu que não viu kkkkkk

2020-06-04 20:42 UTC, elaynelemos commented
> > Sugiro que remova a variável de entrada para licença no `cookiecutter.json`. Além de verificar se alguma referências à licença no template ficou para trás.
> 
> Ja foi removido, tu que não viu kkkkkk

Valha, tô cega.

2020-06-04 21:47 UTC, LEMSantos commented
> Adicionar `pytest-cov` às dependências de dev.

Resolvido

2020-06-05 11:34 UTC, denissonleal approved these changes

2020-06-05 11:35 UTC, merged