Hotfix/update readmes
Sysvale/cookiecutter-data-science pull request #4
Opened 2020-06-05 19:18 UTC by elaynelemos

2020-06-08 14:57 UTC, denissonleal requested changes

2020-06-08 14:57 UTC, denissonleal commented on {{ cookiecutter.repo_name }}/README.md
> +docker-compose up prod
é interessante colocar o processo de produção separado. Pq o dev e o jupyter são para de desenvoltimento.

2020-06-08 14:57 UTC, denissonleal commented on {{ cookiecutter.repo_name }}/README.md
> +
tb acho interessante ter o processo de rodar algo no container com o `docker-compose exec`...

2020-06-08 14:57 UTC, denissonleal commented on {{ cookiecutter.repo_name }}/README.md
> +
e para finalizar poderia ter os comandos para pausar e para parar os containers :)

2020-06-09 19:13 UTC, elaynelemos commented
@denissonleal, readme refatorado.

2020-06-10 18:32 UTC, LEMSantos approved these changes

2020-06-11 11:24 UTC, elaynelemos commented
> @denissonleal, readme refatorado.

Agora vai.

2020-06-11 11:53 UTC, denissonleal approved these changes

2020-06-11 11:53 UTC, merged